### ISSUE TITLE
Lombok error

### ISSUE THREAD

**Issue by 1044886782** [zhulinn/SpringBoot-Angular7-Online-Shopping-Store#1]
I don't know why if i implement the project the "@" function throws : can not found the function getXXX()

**Comment by zhulinn** [comment]
Which IDE are you using? You need to install Lombok plugin in your IDE for Lombok support, otherwise the IDE would complain get/set function not found. If your are using Intellij, [check that](https://plugins.jetbrains.com/plugin/6317-lombok).

**Comment by 1044886782** [comment]
> Which IDE are you using? You need to install Lombok plugin in your IDE for Lombok support, otherwise the IDE would complain get/set function not found. If your are using Intellij, [check that](https://github.com/mplushnikov/lombok-intellij-plugin).

I finally solved it by restart the project several times and changing dependency version. 
By the way, cause i didn't have the experience of the Full-Stack program , just keep on learning 请多关照
