### ISSUE TITLE
Cant find object

### ISSUE THREAD

**Issue by sh4mz** [zhulinn/SpringBoot-Angular7-Online-Shopping-Store#2]
May i know what the environment you use? im getting this using openjdk13.. 

![image](https://user-images.githubusercontent.com/6504649/70589295-59333400-1c0a-11ea-83a6-14cb35ce791e.png)

**Comment by sh4mz** [comment]
Well i found the solution already.. just place lombok.jar (need to rename if you get from .m2 folder) in the same place with STS. Edit SpringToolSuite.ini and add 

-vmargs
-javaagent:lombok.jar

ref : https://stackoverflow.com/questions/35842751/lombok-not-working-with-sts

**Comment by zhulinn** [comment]
You need to install Lombok plugin in your IDE for Lombok support. If your are using Intellij, check that.
