### ISSUE TITLE
broken install

### ISSUE THREAD

**Issue by WhiteBite** [zhulinn/SpringBoot-Angular7-Online-Shopping-Store#3]
C:\Users\Lord\source\repos\SpringBoot-Angular7-Online-Shopping-Store-master\frontend>npm install

> node-sass@4.10.0 install C:\Users\Lord\source\repos\SpringBoot-Angular7-Online-Shopping-Store-master\frontend\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 postinstall C:\Users\Lord\source\repos\SpringBoot-Angular7-Online-Shopping-Store-master\frontend\node_modules\node-sass
> node scripts/build.js

**Comment by MKraev** [comment]
Hi WhiteBite,

Did you manage to run the application in the end?

**Comment by WhiteBite** [comment]
> Привет, WhiteBite,
> 
> Удалось ли в итоге запустить приложение?

Yes
